### PR TITLE
Update README.md. Removed hardcoded password hashes

### PR DESCRIPTION
**Pull request by mudspot**
CHANGELOG as follows

1. Updated README.md
There was a missing step about setting up 41_authentication

2. Instead of hardcoded hash for password, the setup now accepts plain text password. Postgres then handles the bcrypting via the crypt function provided by pycrypto extension

3. Added code to delete 41_authentication.sql for security reasons

Signed-off-by: Terry Lee <terry.lee@nogginasia.com>

### CODE REVIEW

**Comment by AndriusA** [comment]
Thanks!

We actually prefer using password hashes as opposed to passing in raw passwords as it allows us to never expose plaintext passwords in provisioning. Hardcoded or not is fine because these are just the defaults and in practice the real values should be set as environment variables.

Perhaps a compromise would be to allow both plaintext and hashed passwords (suffix of `_HASH` in the latter case)? That would need to add some conditional handling in the scripts though, would you be willing to do that?

**Comment by mudspot** [comment]
Yup I understand. I'll get that going.

**Comment by mudspot** [comment]
@AndriusA , codes updated as requested.

CHANGELOG as follows.

1. HAT Owner password
Accepts *HAT_OWNER_PASSWORD* environment variable as plain text password. Automatically hashed during data evolution step.
Accepts *HAT_OWNER_PASSWORD_HASH* environment variable as hashed password
HAT_OWNER_PASSWORD_HASH has priority if both are set

2. HAT Platform password
Accepts *HAT_PLATFORM_PASSWORD* environment variable as plain text password. Automatically hashed during data evolution step.
Accepts *HAT_PLATFORM_PASSWORD_HASH* environment variable as hashed password
HAT_PLATFORM_PASSWORD_HASH has priority if both are set

3. README.md
Updated to describe above. New section added

4. Added code to delete evolution.sql for security reasons after evolution.

Signed-off-by: Terry Lee terry.lee@nogginasia.com

**Comment by AndriusA** [comment]
Thank you, looks good to me and very useful

**Pull request merged**
